# Generated by Django 3.2.19 on 2023-06-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foret',
            fields=[
                ('nom', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('superficie', models.FloatField(help_text='Superficie en hectares (ha)')),
            ],
        ),
        migrations.CreateModel(
            name='Arbre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordonnees', models.CharField(max_length=200)),
                ('espece', models.CharField(max_length=200)),
                ('circonference', models.CharField(help_text='Circonférence en (cm)', max_length=50)),
                ('hauteur', models.CharField(help_text='Hauteur en (m)', max_length=50)),
                ('foret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foret')),
            ],
        ),
    ]
